// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	auth "main.go/internal/auth"
	types "main.go/internal/types"
)

// MockIUseCase is a mock of IUseCase interface.
type MockIUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIUseCaseMockRecorder
}

// MockIUseCaseMockRecorder is the mock recorder for MockIUseCase.
type MockIUseCaseMockRecorder struct {
	mock *MockIUseCase
}

// NewMockIUseCase creates a new mock instance.
func NewMockIUseCase(ctrl *gomock.Controller) *MockIUseCase {
	mock := &MockIUseCase{ctrl: ctrl}
	mock.recorder = &MockIUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUseCase) EXPECT() *MockIUseCaseMockRecorder {
	return m.recorder
}

// DeleteProfile mocks base method.
func (m *MockIUseCase) DeleteProfile(sessionID string, ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", sessionID, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockIUseCaseMockRecorder) DeleteProfile(sessionID, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockIUseCase)(nil).DeleteProfile), sessionID, ctx)
}

// GetAllInterests mocks base method.
func (m *MockIUseCase) GetAllInterests(ctx context.Context) ([]*auth.Interest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInterests", ctx)
	ret0, _ := ret[0].([]*auth.Interest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInterests indicates an expected call of GetAllInterests.
func (mr *MockIUseCaseMockRecorder) GetAllInterests(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInterests", reflect.TypeOf((*MockIUseCase)(nil).GetAllInterests), ctx)
}

// GetMatches mocks base method.
func (m *MockIUseCase) GetMatches(profile types.UserID, nameFilter string, ctx context.Context) ([]auth.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatches", profile, nameFilter, ctx)
	ret0, _ := ret[0].([]auth.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatches indicates an expected call of GetMatches.
func (mr *MockIUseCaseMockRecorder) GetMatches(profile, nameFilter, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatches", reflect.TypeOf((*MockIUseCase)(nil).GetMatches), profile, nameFilter, ctx)
}

// GetName mocks base method.
func (m *MockIUseCase) GetName(userID types.UserID, ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName", userID, ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetName indicates an expected call of GetName.
func (mr *MockIUseCaseMockRecorder) GetName(userID, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIUseCase)(nil).GetName), userID, ctx)
}

// GetProfile mocks base method.
func (m *MockIUseCase) GetProfile(params auth.ProfileGetParams, ctx context.Context) ([]auth.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", params, ctx)
	ret0, _ := ret[0].([]auth.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockIUseCaseMockRecorder) GetProfile(params, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockIUseCase)(nil).GetProfile), params, ctx)
}

// IsAuthenticated mocks base method.
func (m *MockIUseCase) IsAuthenticated(sessionID string, ctx context.Context) (types.UserID, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthenticated", sessionID, ctx)
	ret0, _ := ret[0].(types.UserID)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsAuthenticated indicates an expected call of IsAuthenticated.
func (mr *MockIUseCaseMockRecorder) IsAuthenticated(sessionID, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthenticated", reflect.TypeOf((*MockIUseCase)(nil).IsAuthenticated), sessionID, ctx)
}

// Login mocks base method.
func (m *MockIUseCase) Login(email, password string, ctx context.Context) (*auth.Profile, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", email, password, ctx)
	ret0, _ := ret[0].(*auth.Profile)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockIUseCaseMockRecorder) Login(email, password, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIUseCase)(nil).Login), email, password, ctx)
}

// Logout mocks base method.
func (m *MockIUseCase) Logout(sessionID string, ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", sessionID, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockIUseCaseMockRecorder) Logout(sessionID, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockIUseCase)(nil).Logout), sessionID, ctx)
}

// Registration mocks base method.
func (m *MockIUseCase) Registration(body auth.RegitstrationBody, ctx context.Context) (*auth.Profile, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Registration", body, ctx)
	ret0, _ := ret[0].(*auth.Profile)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Registration indicates an expected call of Registration.
func (mr *MockIUseCaseMockRecorder) Registration(body, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Registration", reflect.TypeOf((*MockIUseCase)(nil).Registration), body, ctx)
}

// UpdateProfile mocks base method.
func (m *MockIUseCase) UpdateProfile(SID string, profile auth.ProfileUpdateRequest, ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", SID, profile, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockIUseCaseMockRecorder) UpdateProfile(SID, profile, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockIUseCase)(nil).UpdateProfile), SID, profile, ctx)
}

// MockPersonStorage is a mock of PersonStorage interface.
type MockPersonStorage struct {
	ctrl     *gomock.Controller
	recorder *MockPersonStorageMockRecorder
}

// MockPersonStorageMockRecorder is the mock recorder for MockPersonStorage.
type MockPersonStorageMockRecorder struct {
	mock *MockPersonStorage
}

// NewMockPersonStorage creates a new mock instance.
func NewMockPersonStorage(ctrl *gomock.Controller) *MockPersonStorage {
	mock := &MockPersonStorage{ctrl: ctrl}
	mock.recorder = &MockPersonStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonStorage) EXPECT() *MockPersonStorageMockRecorder {
	return m.recorder
}

// AddAccount mocks base method.
func (m *MockPersonStorage) AddAccount(ctx context.Context, Name, Birhday, Gender, Email, Password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccount", ctx, Name, Birhday, Gender, Email, Password)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAccount indicates an expected call of AddAccount.
func (mr *MockPersonStorageMockRecorder) AddAccount(ctx, Name, Birhday, Gender, Email, Password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccount", reflect.TypeOf((*MockPersonStorage)(nil).AddAccount), ctx, Name, Birhday, Gender, Email, Password)
}

// Delete mocks base method.
func (m *MockPersonStorage) Delete(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPersonStorageMockRecorder) Delete(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPersonStorage)(nil).Delete), ctx, sessionID)
}

// Get mocks base method.
func (m *MockPersonStorage) Get(ctx context.Context, filter *auth.PersonGetFilter) ([]*auth.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].([]*auth.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPersonStorageMockRecorder) Get(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPersonStorage)(nil).Get), ctx, filter)
}

// GetMatch mocks base method.
func (m *MockPersonStorage) GetMatch(ctx context.Context, person1ID types.UserID) ([]types.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatch", ctx, person1ID)
	ret0, _ := ret[0].([]types.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatch indicates an expected call of GetMatch.
func (mr *MockPersonStorageMockRecorder) GetMatch(ctx, person1ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatch", reflect.TypeOf((*MockPersonStorage)(nil).GetMatch), ctx, person1ID)
}

// Update mocks base method.
func (m *MockPersonStorage) Update(ctx context.Context, person auth.Person) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, person)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPersonStorageMockRecorder) Update(ctx, person interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPersonStorage)(nil).Update), ctx, person)
}

// MockSessionStorage is a mock of SessionStorage interface.
type MockSessionStorage struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStorageMockRecorder
}

// MockSessionStorageMockRecorder is the mock recorder for MockSessionStorage.
type MockSessionStorageMockRecorder struct {
	mock *MockSessionStorage
}

// NewMockSessionStorage creates a new mock instance.
func NewMockSessionStorage(ctrl *gomock.Controller) *MockSessionStorage {
	mock := &MockSessionStorage{ctrl: ctrl}
	mock.recorder = &MockSessionStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStorage) EXPECT() *MockSessionStorageMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionStorage) CreateSession(ctx context.Context, session auth.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionStorageMockRecorder) CreateSession(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionStorage)(nil).CreateSession), ctx, session)
}

// DeleteSession mocks base method.
func (m *MockSessionStorage) DeleteSession(ctx context.Context, SID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, SID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionStorageMockRecorder) DeleteSession(ctx, SID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionStorage)(nil).DeleteSession), ctx, SID)
}

// GetBySID mocks base method.
func (m *MockSessionStorage) GetBySID(ctx context.Context, SID string) (*auth.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySID", ctx, SID)
	ret0, _ := ret[0].(*auth.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySID indicates an expected call of GetBySID.
func (mr *MockSessionStorageMockRecorder) GetBySID(ctx, SID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySID", reflect.TypeOf((*MockSessionStorage)(nil).GetBySID), ctx, SID)
}

// MockInterestStorage is a mock of InterestStorage interface.
type MockInterestStorage struct {
	ctrl     *gomock.Controller
	recorder *MockInterestStorageMockRecorder
}

// MockInterestStorageMockRecorder is the mock recorder for MockInterestStorage.
type MockInterestStorageMockRecorder struct {
	mock *MockInterestStorage
}

// NewMockInterestStorage creates a new mock instance.
func NewMockInterestStorage(ctrl *gomock.Controller) *MockInterestStorage {
	mock := &MockInterestStorage{ctrl: ctrl}
	mock.recorder = &MockInterestStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterestStorage) EXPECT() *MockInterestStorageMockRecorder {
	return m.recorder
}

// CreatePersonInterests mocks base method.
func (m *MockInterestStorage) CreatePersonInterests(ctx context.Context, personID types.UserID, interestID []types.InterestID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePersonInterests", ctx, personID, interestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePersonInterests indicates an expected call of CreatePersonInterests.
func (mr *MockInterestStorageMockRecorder) CreatePersonInterests(ctx, personID, interestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePersonInterests", reflect.TypeOf((*MockInterestStorage)(nil).CreatePersonInterests), ctx, personID, interestID)
}

// DeletePersonInterests mocks base method.
func (m *MockInterestStorage) DeletePersonInterests(ctx context.Context, personID types.UserID, interestID []types.InterestID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePersonInterests", ctx, personID, interestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePersonInterests indicates an expected call of DeletePersonInterests.
func (mr *MockInterestStorageMockRecorder) DeletePersonInterests(ctx, personID, interestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePersonInterests", reflect.TypeOf((*MockInterestStorage)(nil).DeletePersonInterests), ctx, personID, interestID)
}

// Get mocks base method.
func (m *MockInterestStorage) Get(ctx context.Context, filter *auth.InterestGetFilter) ([]*auth.Interest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].([]*auth.Interest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInterestStorageMockRecorder) Get(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInterestStorage)(nil).Get), ctx, filter)
}

// GetPersonInterests mocks base method.
func (m *MockInterestStorage) GetPersonInterests(ctx context.Context, personID types.UserID) ([]*auth.Interest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonInterests", ctx, personID)
	ret0, _ := ret[0].([]*auth.Interest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonInterests indicates an expected call of GetPersonInterests.
func (mr *MockInterestStorageMockRecorder) GetPersonInterests(ctx, personID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonInterests", reflect.TypeOf((*MockInterestStorage)(nil).GetPersonInterests), ctx, personID)
}

// MockImageStorage is a mock of ImageStorage interface.
type MockImageStorage struct {
	ctrl     *gomock.Controller
	recorder *MockImageStorageMockRecorder
}

// MockImageStorageMockRecorder is the mock recorder for MockImageStorage.
type MockImageStorageMockRecorder struct {
	mock *MockImageStorage
}

// NewMockImageStorage creates a new mock instance.
func NewMockImageStorage(ctrl *gomock.Controller) *MockImageStorage {
	mock := &MockImageStorage{ctrl: ctrl}
	mock.recorder = &MockImageStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageStorage) EXPECT() *MockImageStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockImageStorage) Get(ctx context.Context, userID int64) ([]auth.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].([]auth.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockImageStorageMockRecorder) Get(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockImageStorage)(nil).Get), ctx, userID)
}
