version: "3.8" # версия вашего docker-compose
services: # имеджи, которые запустятся по вашему желанию
  app:
    build: db
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8085:8085"
    env_file:
      - .env 

  db: # название моего имеджа
    image: postgres:12-alpine # скачает image postgres 12 версии
    restart: always
    volumes: # часть настроек для хранения данных, пока для нас это не важно
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tpTinder
      POSTGRES_PASSWORD: postgres

  adminer: # adminer db client
    image: adminer
    ports:
      - 8000:8080
    depends_on:
      - db

volumes: # часть настроек для хранения данных
  postgresdb-data:
    driver: local