apiPath: "/api/v1/"

server:
  host: "0.0.0.0"
  port: ":8081"
  swaggerPort: ":8085"
  timeout: 5

database:
  host: "localhost"
  port: "5432"
  dbname: "tpTinder"
  user: "postgres"
  password: "postgres"