apiPath: "/api/v1/"
server:
  host: "0.0.0.0"
  port: ":8080"
  swaggerPort: ":8085"
  timeout: 5

database:
  host: "db"
  port: "5432"
  dbname: "tpTinder"
  user: "postgres"
  password: "postgres"
  max_open_conns: 10